import { createPayment, updatePayment, voidPayment } from "@/app/actions/operations";
import { ConfirmAction } from "@/components/confirm-action";
import { CrudDialog } from "@/components/crud-dialog";
import { Field, SelectField, TextAreaField } from "@/components/form-fields";
import { EmptyState, Flash, PageHeader, StatusBadge } from "@/components/page-ui";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { requireUser } from "@/lib/auth";
import { shortDate, zar } from "@/lib/format";
import { prisma } from "@/lib/prisma";

const methods = ["EFT", "CASH", "CARD", "OTHER"].map((value) => ({ value, label: value }));

export default async function PaymentsPage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  const user = await requireUser(); const params = await searchParams;
  const [payments, invoices] = await Promise.all([
    prisma.payment.findMany({ where: { organizationId: user.organizationId }, include: { customer: true, allocations: { include: { invoice: true } } }, orderBy: { paymentDate: "desc" } }),
    prisma.invoice.findMany({ where: { organizationId: user.organizationId, status: { in: ["SENT", "PART_PAID", "OVERDUE"] } }, include: { customer: true, allocations: { include: { payment: true } } }, orderBy: { dueDate: "asc" } }),
  ]);
  const openInvoices = invoices.map((invoice) => ({ invoice, paid: invoice.allocations.filter((a) => a.payment.status === "ACTIVE").reduce((sum, a) => sum + Number(a.amount), 0) })).filter(({ invoice, paid }) => paid < Number(invoice.total));
  const create = <CrudDialog title="Capture customer receipt" description="Allocate a bank receipt to one customer invoice. The invoice balance updates in the same database transaction." action={createPayment} triggerLabel="Capture receipt"><SelectField name="invoiceId" label="Open invoice" options={openInvoices.map(({ invoice, paid }) => ({ value: invoice.id, label: `${invoice.invoiceNumber} · ${invoice.customer.name} · ${zar.format(Number(invoice.total) - paid)} open` }))} /><Field name="amount" label="Amount received (R)" type="number" min={0.01} step="0.01" required /><Field name="paymentDate" label="Payment date" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required /><SelectField name="method" label="Payment method" defaultValue="EFT" options={methods} /><Field name="reference" label="Bank reference" required /><TextAreaField name="notes" label="Notes" className="sm:col-span-2" /></CrudDialog>;
  return <main className="mx-auto w-full max-w-[1480px] p-4 md:p-7"><PageHeader title="Customer receipts" description="Capture, update and reverse incoming payments with full invoice allocation history." action={openInvoices.length ? create : undefined} /><Flash success={params.success} error={params.error} />{payments.length ? <Card className="border-slate-200 shadow-none"><CardContent className="px-0"><Table><TableHeader><TableRow><TableHead className="pl-6">Receipt</TableHead><TableHead>Customer</TableHead><TableHead>Invoice</TableHead><TableHead>Date</TableHead><TableHead>Method</TableHead><TableHead>Reference</TableHead><TableHead>Amount</TableHead><TableHead>Status</TableHead><TableHead className="pr-6 text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{payments.map((payment) => <TableRow key={payment.id}><TableCell className="pl-6 font-semibold">{payment.paymentNumber}</TableCell><TableCell>{payment.customer.name}</TableCell><TableCell>{payment.allocations.map((a) => a.invoice.invoiceNumber).join(", ")}</TableCell><TableCell>{shortDate(payment.paymentDate)}</TableCell><TableCell>{payment.method}</TableCell><TableCell>{payment.reference}</TableCell><TableCell className="font-semibold">{zar.format(Number(payment.amount))}</TableCell><TableCell><StatusBadge status={payment.status} /></TableCell><TableCell className="pr-6"><div className="flex justify-end gap-1">{payment.status === "ACTIVE" && <CrudDialog mode="edit" title={`Edit ${payment.paymentNumber}`} description="The allocated amount cannot be changed. Void and recapture if the amount is incorrect." action={updatePayment}><input type="hidden" name="id" value={payment.id} /><Field name="paymentDate" label="Payment date" type="date" defaultValue={payment.paymentDate.toISOString().slice(0, 10)} required /><SelectField name="method" label="Payment method" defaultValue={payment.method} options={methods} /><Field name="reference" label="Bank reference" defaultValue={payment.reference} required /><TextAreaField name="notes" label="Notes" defaultValue={payment.notes} className="sm:col-span-2" /></CrudDialog>}{payment.status === "ACTIVE" && <ConfirmAction action={voidPayment} id={payment.id} title="Reverse this receipt?" description="The payment will be marked void and the invoice balance will be restored. The record remains in the audit trail." label="Void receipt" reason />}</div></TableCell></TableRow>)}</TableBody></Table></CardContent></Card> : <EmptyState title="No receipts yet" description={openInvoices.length ? "Capture the first customer payment against an open invoice." : "Receipts can be captured once an invoice has been issued."} action={openInvoices.length ? create : undefined} />}</main>;
}
