import { Search } from "lucide-react";
import type { JobStatus } from "@/generated/prisma/client";
import { archiveJob, createJob, updateJob } from "@/app/actions/operations";
import { ConfirmAction } from "@/components/confirm-action";
import { CrudDialog } from "@/components/crud-dialog";
import { CheckField, Field, SelectField, TextAreaField } from "@/components/form-fields";
import { EmptyState, Flash, PageHeader, StatusBadge } from "@/components/page-ui";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { requireUser } from "@/lib/auth";
import { shortDate, zar } from "@/lib/format";
import { prisma } from "@/lib/prisma";

const statusOptions = ["DRAFT", "SCHEDULED", "IN_TRANSIT", "DELIVERED", "INVOICED"] as JobStatus[];

export default async function JobsPage({ searchParams }: { searchParams: Promise<{ q?: string; success?: string; error?: string }> }) {
  const user = await requireUser(); const params = await searchParams; const q = params.q?.trim() ?? "";
  const [jobs, customers, carriers] = await Promise.all([
    prisma.job.findMany({ where: { organizationId: user.organizationId, ...(q ? { OR: [{ jobNumber: { contains: q } }, { origin: { contains: q } }, { destination: { contains: q } }, { customer: { name: { contains: q } } }, { carrier: { name: { contains: q } } }] } : {}) }, include: { customer: true, carrier: true, settlement: true }, orderBy: { createdAt: "desc" } }),
    prisma.customer.findMany({ where: { organizationId: user.organizationId, isActive: true }, orderBy: { name: "asc" } }),
    prisma.carrier.findMany({ where: { organizationId: user.organizationId, isActive: true }, orderBy: { name: "asc" } }),
  ]);
  const ready = customers.length > 0 && carriers.length > 0;
  const create = <CrudDialog title="New subcontracted job" description="Record the sell rate and carrier cost together so margin is controlled from the start." action={createJob} triggerLabel="Create job"><JobFields customers={customers} carriers={carriers} /></CrudDialog>;
  return <main className="mx-auto w-full max-w-[1600px] p-4 md:p-7"><PageHeader title="Subcontracted jobs" description="Track each load from allocation through delivery, invoicing and closure." action={ready ? create : undefined} /><Flash success={params.success} error={params.error} /><form className="mb-4 flex max-w-md gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><Input name="q" defaultValue={q} placeholder="Search jobs…" className="bg-white pl-9" /></div><Button variant="outline">Search</Button></form>{jobs.length ? <Card className="border-slate-200 shadow-none"><CardContent className="px-0"><Table><TableHeader><TableRow><TableHead className="pl-6">Job</TableHead><TableHead>Customer</TableHead><TableHead>Route</TableHead><TableHead>Carrier</TableHead><TableHead>Load date</TableHead><TableHead>Sell / cost</TableHead><TableHead>Margin</TableHead><TableHead>Status</TableHead><TableHead className="pr-6 text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{jobs.map((job) => <TableRow key={job.id}><TableCell className="pl-6"><p className="font-semibold">{job.jobNumber}</p><p className="text-xs text-slate-500">{job.customerReference ?? "No customer ref"}</p></TableCell><TableCell>{job.customer.name}</TableCell><TableCell><p>{job.origin}</p><p className="text-xs text-slate-500">to {job.destination}</p></TableCell><TableCell>{job.carrier?.name ?? "Unassigned"}</TableCell><TableCell>{shortDate(job.loadDate)}</TableCell><TableCell><p>{zar.format(Number(job.customerAmount))}</p><p className="text-xs text-slate-500">Cost {zar.format(Number(job.carrierAmount))}</p></TableCell><TableCell className="font-semibold text-emerald-700">{zar.format(Number(job.customerAmount) - Number(job.carrierAmount))}</TableCell><TableCell><StatusBadge status={job.status} /></TableCell><TableCell className="pr-6"><div className="flex justify-end gap-1">{!["CLOSED", "CANCELLED"].includes(job.status) && <CrudDialog mode="edit" title={`Edit ${job.jobNumber}`} description="Update operational details, status and proof of delivery." action={updateJob}><input type="hidden" name="id" value={job.id} /><JobFields job={job} customers={customers} carriers={carriers} /></CrudDialog>}{!["CLOSED", "CANCELLED"].includes(job.status) && <ConfirmAction action={archiveJob} id={job.id} title="Cancel this job?" description="The job and its unpaid settlement will be marked cancelled/void. Invoiced or paid jobs cannot be cancelled." label="Cancel job" />}</div></TableCell></TableRow>)}</TableBody></Table></CardContent></Card> : <EmptyState title={ready ? "No jobs yet" : "Set up customers and carriers first"} description={ready ? "Create your first job. The linked carrier settlement will be created automatically." : "At least one active customer and one active carrier are required before a job can be created."} action={ready ? create : undefined} />}</main>;
}

function JobFields({ job, customers, carriers }: { job?: { customerId: string; carrierId: string | null; status: JobStatus; origin: string; destination: string; loadDate: Date; description: string; customerReference: string | null; vehicleReg: string | null; driverName: string | null; driverPhone: string | null; customerAmount: unknown; carrierAmount: unknown; podUrl: string | null; podReceivedAt: Date | null; notes: string | null }; customers: { id: string; code: string; name: string }[]; carriers: { id: string; code: string; name: string }[] }) { return <><SelectField name="customerId" label="Customer" defaultValue={job?.customerId} options={customers.map((x) => ({ value: x.id, label: `${x.code} · ${x.name}` }))} /><SelectField name="carrierId" label="Carrier" defaultValue={job?.carrierId} options={carriers.map((x) => ({ value: x.id, label: `${x.code} · ${x.name}` }))} />{job && <SelectField name="status" label="Status" defaultValue={job.status} options={statusOptions.map((value) => ({ value, label: value.toLowerCase().replaceAll("_", " ") }))} />}<Field name="loadDate" label="Load date" type="date" defaultValue={job?.loadDate.toISOString().slice(0, 10) ?? new Date().toISOString().slice(0, 10)} required /><Field name="origin" label="Collection point" defaultValue={job?.origin} required /><Field name="destination" label="Delivery point" defaultValue={job?.destination} required /><Field name="customerReference" label="Customer reference" defaultValue={job?.customerReference} /><Field name="vehicleReg" label="Vehicle registration" defaultValue={job?.vehicleReg} /><Field name="driverName" label="Driver name" defaultValue={job?.driverName} /><Field name="driverPhone" label="Driver phone" defaultValue={job?.driverPhone} /><Field name="customerAmount" label="Customer rate (R)" type="number" min={0} step="0.01" defaultValue={job ? Number(job.customerAmount) : undefined} required /><Field name="carrierAmount" label="Carrier cost (R)" type="number" min={0} step="0.01" defaultValue={job ? Number(job.carrierAmount) : undefined} required /><TextAreaField name="description" label="Load description" defaultValue={job?.description} required className="sm:col-span-2" /><Field name="podUrl" label="Proof-of-delivery URL" defaultValue={job?.podUrl} /><div className="self-end"><CheckField name="podReceived" label="Proof of delivery received" defaultChecked={!!job?.podReceivedAt} /></div><TextAreaField name="notes" label="Internal notes" defaultValue={job?.notes} className="sm:col-span-2" /></>; }
