import { Search } from "lucide-react";
import { createCarrier, setCarrierActive, updateCarrier } from "@/app/actions/operations";
import { ConfirmAction } from "@/components/confirm-action";
import { CrudDialog } from "@/components/crud-dialog";
import { CheckField, Field } from "@/components/form-fields";
import { EmptyState, Flash, PageHeader, StatusBadge } from "@/components/page-ui";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { requireUser } from "@/lib/auth";
import { shortDate, zar } from "@/lib/format";
import { prisma } from "@/lib/prisma";

export default async function CarriersPage({ searchParams }: { searchParams: Promise<{ q?: string; success?: string; error?: string }> }) {
  const user = await requireUser(); const params = await searchParams; const q = params.q?.trim() ?? "";
  const carriers = await prisma.carrier.findMany({ where: { organizationId: user.organizationId, ...(q ? { OR: [{ name: { contains: q } }, { code: { contains: q } }, { contactName: { contains: q } }] } : {}) }, include: { settlements: { where: { status: { notIn: ["PAID", "VOID"] } } }, _count: { select: { jobs: true } } }, orderBy: [{ isActive: "desc" }, { name: "asc" }] });
  const create = <CrudDialog title="New carrier" description="Add a subcontracted trucking company and its compliance details." action={createCarrier} triggerLabel="Add carrier"><CarrierFields /></CrudDialog>;
  return <main className="mx-auto w-full max-w-[1480px] p-4 md:p-7"><PageHeader title="Carriers" description="Subcontractor contacts, banking verification, insurance and payment exposure." action={create} /><Flash success={params.success} error={params.error} /><form className="mb-4 flex max-w-md gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><Input name="q" defaultValue={q} placeholder="Search carriers…" className="bg-white pl-9" /></div><Button variant="outline">Search</Button></form>{carriers.length ? <Card className="border-slate-200 shadow-none"><CardContent className="px-0"><Table><TableHeader><TableRow><TableHead className="pl-6">Carrier</TableHead><TableHead>Contact</TableHead><TableHead>Banking</TableHead><TableHead>Insurance expiry</TableHead><TableHead>Jobs</TableHead><TableHead>Unpaid</TableHead><TableHead>Status</TableHead><TableHead className="pr-6 text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{carriers.map((carrier) => <TableRow key={carrier.id}><TableCell className="pl-6"><p className="font-semibold">{carrier.name}</p><p className="text-xs text-slate-500">{carrier.code}</p></TableCell><TableCell><p>{carrier.contactName ?? "—"}</p><p className="text-xs text-slate-500">{carrier.phone ?? carrier.email ?? "No contact"}</p></TableCell><TableCell><StatusBadge status={carrier.bankVerifiedAt ? "VERIFIED" : "PENDING"} /></TableCell><TableCell>{carrier.insuranceExpiresAt ? shortDate(carrier.insuranceExpiresAt) : "—"}</TableCell><TableCell>{carrier._count.jobs}</TableCell><TableCell className="font-semibold">{zar.format(carrier.settlements.reduce((sum, s) => sum + Number(s.amount), 0))}</TableCell><TableCell><StatusBadge status={carrier.isActive ? "ACTIVE" : "ARCHIVED"} /></TableCell><TableCell className="pr-6"><div className="flex justify-end gap-1"><CrudDialog mode="edit" title={`Edit ${carrier.name}`} description="Update contact, compliance and verified bank status." action={updateCarrier}><input type="hidden" name="id" value={carrier.id} /><CarrierFields carrier={carrier} /></CrudDialog><ConfirmAction action={setCarrierActive} id={carrier.id} title={carrier.isActive ? "Archive carrier?" : "Restore carrier?"} description={carrier.isActive ? "Existing history remains, but this carrier cannot be allocated to new jobs." : "The carrier will be available for allocation again."} label={carrier.isActive ? "Archive" : "Restore"} restore={!carrier.isActive} /></div></TableCell></TableRow>)}</TableBody></Table></CardContent></Card> : <EmptyState title="No carriers yet" description="Add a verified subcontractor before creating your first job." action={create} />}</main>;
}

function CarrierFields({ carrier }: { carrier?: { name: string; contactName: string | null; email: string | null; phone: string | null; registrationNo: string | null; vatNumber: string | null; bankName: string | null; bankAccountName: string | null; bankAccountLast4: string | null; bankVerifiedAt: Date | null; insuranceExpiresAt: Date | null } }) { return <><Field name="name" label="Carrier name" defaultValue={carrier?.name} required /><Field name="contactName" label="Contact person" defaultValue={carrier?.contactName} /><Field name="email" label="Email" type="email" defaultValue={carrier?.email} /><Field name="phone" label="Phone" defaultValue={carrier?.phone} /><Field name="registrationNo" label="Registration number" defaultValue={carrier?.registrationNo} /><Field name="vatNumber" label="VAT number" defaultValue={carrier?.vatNumber} /><Field name="bankName" label="Bank name" defaultValue={carrier?.bankName} /><Field name="bankAccountName" label="Account name" defaultValue={carrier?.bankAccountName} /><Field name="bankAccountLast4" label="Account last 4 digits" defaultValue={carrier?.bankAccountLast4} /><Field name="insuranceExpiresAt" label="Insurance expiry" type="date" defaultValue={carrier?.insuranceExpiresAt?.toISOString().slice(0, 10)} /><div className="sm:col-span-2"><CheckField name="bankVerified" label="Banking details independently verified" defaultChecked={!!carrier?.bankVerifiedAt} /></div></>; }
