import { Search } from "lucide-react";
import { createCustomer, setCustomerActive, updateCustomer } from "@/app/actions/operations";
import { ConfirmAction } from "@/components/confirm-action";
import { CrudDialog } from "@/components/crud-dialog";
import { Field, TextAreaField } from "@/components/form-fields";
import { EmptyState, Flash, PageHeader, StatusBadge } from "@/components/page-ui";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { requireUser } from "@/lib/auth";
import { zar } from "@/lib/format";
import { prisma } from "@/lib/prisma";

export default async function CustomersPage({ searchParams }: { searchParams: Promise<{ q?: string; success?: string; error?: string }> }) {
  const user = await requireUser(); const params = await searchParams; const q = params.q?.trim() ?? "";
  const customers = await prisma.customer.findMany({ where: { organizationId: user.organizationId, ...(q ? { OR: [{ name: { contains: q } }, { code: { contains: q } }, { billingEmail: { contains: q } }] } : {}) }, include: { invoices: { where: { status: { not: "VOID" } }, include: { allocations: { include: { payment: true } } } }, _count: { select: { jobs: true } } }, orderBy: [{ isActive: "desc" }, { name: "asc" }] });
  const create = <CrudDialog title="New customer" description="Create a billing profile for a customer." action={createCustomer} triggerLabel="Add customer"><CustomerFields /></CrudDialog>;
  return <main className="mx-auto w-full max-w-[1480px] p-4 md:p-7"><PageHeader title="Customers" description="Manage billing details, payment terms and customer balances." action={create} /><Flash success={params.success} error={params.error} /><form className="mb-4 flex max-w-md gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><Input name="q" defaultValue={q} placeholder="Search customers…" className="bg-white pl-9" /></div><Button variant="outline">Search</Button></form>{customers.length ? <Card className="border-slate-200 shadow-none"><CardContent className="px-0"><Table><TableHeader><TableRow><TableHead className="pl-6">Customer</TableHead><TableHead>Contact</TableHead><TableHead>Terms</TableHead><TableHead>Jobs</TableHead><TableHead>Open balance</TableHead><TableHead>Status</TableHead><TableHead className="pr-6 text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{customers.map((customer) => { const balance = customer.invoices.reduce((sum, invoice) => sum + Number(invoice.total) - invoice.allocations.filter((a) => a.payment.status === "ACTIVE").reduce((paid, a) => paid + Number(a.amount), 0), 0); return <TableRow key={customer.id}><TableCell className="pl-6"><p className="font-semibold">{customer.name}</p><p className="text-xs text-slate-500">{customer.code}</p></TableCell><TableCell><p>{customer.billingEmail}</p><p className="text-xs text-slate-500">{customer.phone ?? "No phone"}</p></TableCell><TableCell>{customer.paymentTerms} days</TableCell><TableCell>{customer._count.jobs}</TableCell><TableCell className="font-semibold">{zar.format(balance)}</TableCell><TableCell><StatusBadge status={customer.isActive ? "ACTIVE" : "ARCHIVED"} /></TableCell><TableCell className="pr-6"><div className="flex justify-end gap-1"><CrudDialog mode="edit" title={`Edit ${customer.name}`} description="Update this customer profile." action={updateCustomer}><input type="hidden" name="id" value={customer.id} /><CustomerFields customer={customer} /></CrudDialog><ConfirmAction action={setCustomerActive} id={customer.id} title={customer.isActive ? "Archive customer?" : "Restore customer?"} description={customer.isActive ? "The history remains available, but the customer cannot be selected for new jobs." : "The customer will be available for new work again."} label={customer.isActive ? "Archive" : "Restore"} restore={!customer.isActive} /></div></TableCell></TableRow>; })}</TableBody></Table></CardContent></Card> : <EmptyState title="No customers yet" description="Add your first customer to begin creating logistics jobs and invoices." action={create} />}</main>;
}

function CustomerFields({ customer }: { customer?: { name: string; billingEmail: string; phone: string | null; registrationNo: string | null; vatNumber: string | null; address: string | null; paymentTerms: number } }) { return <><Field name="name" label="Customer name" defaultValue={customer?.name} required /><Field name="billingEmail" label="Billing email" type="email" defaultValue={customer?.billingEmail} required /><Field name="phone" label="Phone" defaultValue={customer?.phone} /><Field name="registrationNo" label="Registration number" defaultValue={customer?.registrationNo} /><Field name="vatNumber" label="VAT number" defaultValue={customer?.vatNumber} /><Field name="paymentTerms" label="Payment terms (days)" type="number" min={0} defaultValue={customer?.paymentTerms ?? 30} required /><TextAreaField name="address" label="Billing address" defaultValue={customer?.address} className="sm:col-span-2" /></>; }
